/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as IndexRoute } from './routes/index';
import { Route as QrRoute } from './routes/qr';

// Create/Update Routes

const QrRouteUpdated = QrRoute.update({
  path: '/qr',
  getParentRoute: () => rootRoute,
} as const);

const IndexRouteUpdated = IndexRoute.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as const);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  type FileRoutesByPath = {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteUpdated;
      parentRoute: typeof rootRoute;
    };
    '/qr': {
      id: '/qr';
      path: '/qr';
      fullPath: '/qr';
      preLoaderRoute: typeof QrRouteUpdated;
      parentRoute: typeof rootRoute;
    };
  };
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute: IndexRouteUpdated,
  QrRoute: QrRouteUpdated,
});

/* prettier-ignore-end */
